
package wcfservice.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "iRegistration", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IRegistration {


    /**
     * 
     * @param year
     * @param semester
     * @return
     *     returns wcfservice.stub.ArrayOfstring
     */
    @WebMethod(action = "http://tempuri.org/iRegistration/list")
    @WebResult(name = "listResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "list", targetNamespace = "http://tempuri.org/", className = "wcfservice.stub.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://tempuri.org/", className = "wcfservice.stub.ListResponse")
    public ArrayOfstring list(
        @WebParam(name = "year", targetNamespace = "http://tempuri.org/")
        String year,
        @WebParam(name = "semester", targetNamespace = "http://tempuri.org/")
        String semester);

    /**
     * 
     * @param stdID
     * @param year
     * @param semester
     * @return
     *     returns wcfservice.stub.ArrayOfstring
     */
    @WebMethod(action = "http://tempuri.org/iRegistration/list2")
    @WebResult(name = "list2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "list2", targetNamespace = "http://tempuri.org/", className = "wcfservice.stub.List2")
    @ResponseWrapper(localName = "list2Response", targetNamespace = "http://tempuri.org/", className = "wcfservice.stub.List2Response")
    public ArrayOfstring list2(
        @WebParam(name = "year", targetNamespace = "http://tempuri.org/")
        String year,
        @WebParam(name = "semester", targetNamespace = "http://tempuri.org/")
        String semester,
        @WebParam(name = "stdID", targetNamespace = "http://tempuri.org/")
        String stdID);

    /**
     * 
     * @param stdID
     * @param course
     * @param section
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/iRegistration/register")
    @WebResult(name = "registerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "register", targetNamespace = "http://tempuri.org/", className = "wcfservice.stub.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://tempuri.org/", className = "wcfservice.stub.RegisterResponse")
    public String register(
        @WebParam(name = "course", targetNamespace = "http://tempuri.org/")
        String course,
        @WebParam(name = "section", targetNamespace = "http://tempuri.org/")
        String section,
        @WebParam(name = "stdID", targetNamespace = "http://tempuri.org/")
        String stdID);

}
