
package wcfservice.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RTService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:12475/RTService.svc?wsdl")
public class RTService
    extends Service
{

    private final static URL RTSERVICE_WSDL_LOCATION;
    private final static WebServiceException RTSERVICE_EXCEPTION;
    private final static QName RTSERVICE_QNAME = new QName("http://tempuri.org/", "RTService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:12475/RTService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RTSERVICE_WSDL_LOCATION = url;
        RTSERVICE_EXCEPTION = e;
    }

    public RTService() {
        super(__getWsdlLocation(), RTSERVICE_QNAME);
    }

    public RTService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RTSERVICE_QNAME, features);
    }

    public RTService(URL wsdlLocation) {
        super(wsdlLocation, RTSERVICE_QNAME);
    }

    public RTService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RTSERVICE_QNAME, features);
    }

    public RTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RTService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRegistration
     */
    @WebEndpoint(name = "BasicHttpBinding_iRegistration")
    public IRegistration getBasicHttpBindingIRegistration() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_iRegistration"), IRegistration.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRegistration
     */
    @WebEndpoint(name = "BasicHttpBinding_iRegistration")
    public IRegistration getBasicHttpBindingIRegistration(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_iRegistration"), IRegistration.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RTSERVICE_EXCEPTION!= null) {
            throw RTSERVICE_EXCEPTION;
        }
        return RTSERVICE_WSDL_LOCATION;
    }

}
